# timeout
timeout = "1200s"
# your website url
baseURL = 'https://handavv.github.io/'
# website title
title = 'David Hangu'
# theme
theme = 'bridget'
# don't touch this
disableKinds = ["section", "taxonomy", "term", "home"]
# robots.txt
enableRobotsTXT = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'
