timeout = "1200s"
baseURL = 'https://handavv.github.io/'
languageCode = 'en-us'
title = 'David Hangu'
theme = 'bridget'

# don't touch this
disableKinds = ["section", "taxonomy", "term", "home"]
enableRobotsTXT = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'
